pkging

diff --git a/.github/workflows/macos.yml b/.github/workflows/macos.yml
--- a/.github/workflows/macos.yml
+++ b/.github/workflows/macos.yml
@@ -44,12 +44,12 @@ jobs:
         run: |
           echo "we're on 12"
           echo "::set-output name=test::output1"
-      - name: Fail 11
-        id: fail11
-        if: matrix.version == 11
-        run: |
-          echo "::set-output name=test::output2"
-          exit 1
+      # - name: Fail 11
+      #   id: fail11
+      #   if: matrix.version == 11
+      #   run: |
+      #     echo "::set-output name=test::output2"
+      #     exit 1
 
       - uses: actions/checkout@v3
         id: checkout
